import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)
pd.set_option('display.max_colwidth', None)


class OutlierAnalyzer:

    def __init__(self):
        
        self.line = '─' * 170


    def check_outlier(self,dataframe, num_cols, num_summary_df,q1_th=0.25,q3_th=0.75, iqr_th=1.5, z_score_th=3, remove=False, cap=False):
            """
            Detects outliers in numerical columns using the appropriate statistical method
            based on each column's distribution, then optionally removes or caps them.

            Detection logic:
            - Normal distribution  → Z-score method (default threshold: ±3 std).
            - Non-normal distribution → IQR method (default multiplier: 1.5).

            Normality is determined from num_summary_df, which must be generated by
            NormalityAnalyzer.num_summary() before calling this method.

            Parameters
            ----------
            dataframe : pd.DataFrame
                The dataset to scan for outliers.
            num_cols : list of str
                Numerical columns to check.
            num_summary_df : pd.DataFrame
                Normality summary produced by num_summary(). Required to select the
                correct detection method per column.
            q1_th : float, optional
                Quantile used as the first quartile (Q1) when applying the IQR method.
                Must be between 0 and 1 (default: 0.25).
            q3_th : float, optional
                Quantile used as the third quartile (Q3) when applying the IQR method.
                Must be between 0 and 1 (default: 0.75).
            iqr_th : float, optional
                IQR multiplier used to set the lower/upper fence (default: 1.5).
            z_score_th : int, optional
                Number of standard deviations used as the Z-score boundary (default: 3).
            remove : bool, optional
                If True, drops all rows containing outliers and returns the cleaned
                dataframe (default: False).
            cap : bool, optional
                If True, clips outlier values to the computed lower/upper boundary
                instead of removing rows (default: False).
                Cannot be used together with remove=True.

            Returns
            -------
            dict
                Outlier report mapping each column name to a dict with keys:
                - 'method'         : str  — 'z-score' or 'IQR'
                - 'outlier_count'  : int  — number of outlier values detected
                - 'outlier_ratio'  : float — outlier_count / total rows

            tuple (dict, pd.DataFrame)
                Returned instead of dict when remove=True or cap=True.
                The second element is the modified dataframe after removal or capping.

            Raises
            ------
            ValueError
                If both remove and cap are True, or if num_cols is empty.

            Notes
            -----
            After using remove=True or cap=True, call num_summary() again before
            running any further analysis, as distribution statistics will have changed.
            """
            if cap and remove:
                raise ValueError('! remove and cap cannot both be True. Choose one.')
            if num_cols:
                print(f"\n{self.line}")
                print(" Outlier Detection ".center(170))
                print(self.line)
                outlier_report = {}
                cleaned_df = dataframe.copy()
                for col in num_cols:
                    data = cleaned_df[col]
                    n = len(data)
                    is_normal = num_summary_df[num_summary_df['Column'] == col]['Result']
                    is_normal = is_normal.values[0] == 'Normal'
                    if is_normal:
                        lower = data.mean() - z_score_th * data.std()
                        upper = data.mean() + z_score_th * data.std()
                        z_scores = np.abs((data - data.mean()) / data.std())
                        outliers = data[z_scores > z_score_th]
                        method = "z-score"
                    else:
                        q1 = data.quantile(q1_th)
                        q3 = data.quantile(q3_th)
                        iqr = q3 - q1
                        lower = q1 - iqr_th * iqr
                        upper = q3 + iqr_th * iqr
                        outliers = data[(data < lower) | (data > upper)]
                        method = "IQR"
                    outlier_ratio = outliers.shape[0] / n
                    outlier_report[col] = {"method": method,
                                        "outlier_count": outliers.shape[0],
                                        "outlier_ratio": outlier_ratio}
                    print(f"Column: {col} | Method: {method} | Outliers: {outliers.shape[0]} ({outliers.shape[0] / n:.2%})")
                    if remove and outliers.shape[0] > 0:
                        cleaned_df = cleaned_df.drop(outliers.index)
                    elif cap and outliers.shape[0] > 0:
                        cleaned_df[col] = cleaned_df[col].clip(lower=lower, upper=upper)
                        print(f"  → '{col}' capped at [{lower:.4f}, {upper:.4f}]")
                if remove:
                    return outlier_report, cleaned_df.reset_index(drop=True)
                elif cap:
                    return outlier_report, cleaned_df
                else:
                    return outlier_report
            else:
                raise ValueError('! num_cols is empty')